# Generated by Django 2.0.9 on 2024-01-31 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dctbapp.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='USER',
        ),
        migrations.RemoveField(
            model_name='request',
            name='IMAGE',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.AddField(
            model_name='request',
            name='FILE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dctbapp.file'),
        ),
    ]
