# Generated by Django 2.0.9 on 2024-02-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0002_auto_20240131_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='price',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
