# Generated by Django 5.0.3 on 2024-03-16 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0003_file_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashvalue', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dctbapp.user')),
            ],
        ),
    ]
