# Generated by Django 5.0.3 on 2024-03-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0004_hashvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='filetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('blocknumber', models.CharField(max_length=200)),
            ],
        ),
    ]
