# Generated by Django 5.0.3 on 2024-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0005_filetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='date',
            new_name='blocknumber',
        ),
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
    ]
