# Generated by Django 5.0.3 on 2024-03-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0006_rename_date_file_blocknumber_remove_file_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='USER',
        ),
    ]
