# Generated by Django 5.0.3 on 2024-03-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0007_remove_file_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='FILE',
            new_name='FILES',
        ),
    ]
