# Generated by Django 5.0.3 on 2024-03-30 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0008_rename_file_files_rename_file_request_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashvalue',
            name='USER',
        ),
        migrations.AddField(
            model_name='hashvalue',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dctbapp.login'),
        ),
    ]
