# Generated by Django 5.0.3 on 2024-03-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dctbapp', '0009_remove_hashvalue_user_hashvalue_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashvalue',
            name='hashvalue',
            field=models.TextField(),
        ),
    ]
